# Generated by Django 4.2 on 2023-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('categoria', models.CharField(choices=[('DESPESA', 'Despesa'), ('RECEITA', 'Receita')], default='', max_length=1000)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
