# Generated by Django 4.2 on 2023-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_financeiro',
            name='consolidado',
            field=models.BooleanField(default=False),
        ),
    ]
