# Generated by Django 4.2 on 2023-04-24 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_registro_financeiro_consolidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_financeiro',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
