# Generated by Django 4.2 on 2023-04-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_registro_financeiro_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_financeiro',
            name='centro_de_custo',
            field=models.CharField(choices=[('JULIO', 'Julio'), ('JESSICA', 'Jessica'), ('CASA', 'Casa')], default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='registro_financeiro',
            name='origem_despesa',
            field=models.CharField(choices=[('CARTAO_ITAU_MASTER_PLATINUM', 'Cartão Itaú Master Platinum'), ('CARTAO_ITAU_VISA_PLATINUM', 'Cartão Itaú Visa Platinum'), ('CARTAO_ITAU_PAO_DE_ACUCAR_VISA_PLATINUM', 'Cartão Itaú Pão de Açucar Visa Platinum'), ('CARTAO_ITAU_XP_VISA_INFINITIVE', 'Cartão Itaú XP Visa Infinitive'), ('CARTAO_MERCADO_PAGO', 'Cartão Mercado Pago')], default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='registro_financeiro',
            name='tipo',
            field=models.CharField(choices=[('DESPESA', 'Despesa'), ('RECEITA', 'Receita')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registro_financeiro',
            name='categoria',
            field=models.CharField(choices=[('DESPESA_FIXA', 'Despesa Fixa'), ('RECEITA_PARCELADA', 'Despesa Parcelada'), ('RECEITA_AVULSA', 'Despesa Avula')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registro_financeiro',
            name='descricao',
            field=models.TextField(),
        ),
    ]
