# Generated by Django 4.2 on 2023-04-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_registro_financeiro_centro_de_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_financeiro',
            name='categoria',
            field=models.CharField(choices=[('DESPESA_FIXA', 'Despesa Fixa'), ('RECEITA_PARCELADA', 'Despesa Parcelada'), ('RECEITA_AVULSA', 'Despesa Avulsa')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registro_financeiro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
