# Generated by Django 4.2 on 2023-04-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_registro_financeiro_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_financeiro',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
