# Generated by Django 4.2 on 2023-04-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_registro_financeiro_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_financeiro',
            name='observacao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registro_financeiro',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
    ]
