# Generated by Django 4.2 on 2023-04-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_registro_financeiro_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_financeiro',
            name='competencia',
            field=models.CharField(choices=[('JANEIRO', 'Janeiro'), ('FEVEREIRO', 'Fevereiro'), ('MARCO', 'Março'), ('ABRIL', 'Abril'), ('MAIO', 'Maio'), ('Junho', 'Junho'), ('JULHO', 'Julho'), ('AGOSTO', 'Agosto'), ('SETEMBRO', 'Setembro'), ('OUTUBRO', 'Outubro'), ('NOVEMBRO', 'Novembro'), ('DEZEMBRO', 'Dezembro/2023')], default='', max_length=1000),
        ),
    ]
