# Generated by Django 4.2 on 2023-04-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_registro_financeiro_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_financeiro',
            name='vencimento',
            field=models.CharField(choices=[('JANEIRO', 'Janeiro/2023'), ('FEVEREIRO', 'Fevereiro/2023'), ('MARCO', 'Março/2023'), ('ABRIL', 'Abril/2023'), ('MAIO', 'Maio/2023'), ('Junho', 'Junho/2023'), ('JULHO', 'Julho/2023'), ('AGOSTO', 'Agosto/2023'), ('SETEMBRO', 'Setembro/2023'), ('OUTUBRO', 'Outubro/2023'), ('NOVEMBRO', 'Novembro/2023'), ('DEZEMBRO', 'Dezembro/2023')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registro_financeiro',
            name='competencia',
            field=models.CharField(choices=[('JANEIRO', 'Janeiro/2023'), ('FEVEREIRO', 'Fevereiro/2023'), ('MARCO', 'Março/2023'), ('ABRIL', 'Abril/2023'), ('MAIO', 'Maio/2023'), ('Junho', 'Junho/2023'), ('JULHO', 'Julho/2023'), ('AGOSTO', 'Agosto/2023'), ('SETEMBRO', 'Setembro/2023'), ('OUTUBRO', 'Outubro/2023'), ('NOVEMBRO', 'Novembro/2023'), ('DEZEMBRO', 'Dezembro/2023')], default='', max_length=1000),
        ),
    ]
