# Generated by Django 4.2 on 2023-04-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_registro_financeiro_parcela_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_financeiro',
            name='origem_despesa',
        ),
        migrations.AddField(
            model_name='registro_financeiro',
            name='origem_debito',
            field=models.CharField(choices=[('CARTAO ITAU MASTER CARD PLATINUM', 'Cartão Itaú Master Platinum'), ('CARTAO ITAU VISA PLATINUM', 'Cartão Itaú Visa Platinum'), ('CARTAO ITAU PAO DE ACUCAR VISA PLATINUM', 'Cartão Itaú Pão de Açucar Visa Platinum'), ('CARTAO ITAU XP VISA_INFINITIVE', 'Cartão Itaú XP Visa Infinitive'), ('CARTAO MERCADO PAGO VISA', 'Cartão Mercado Pago')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registro_financeiro',
            name='categoria',
            field=models.CharField(choices=[('DESPESA FIXA', 'Despesa Fixa'), ('RECEITA PARCELADA', 'Despesa Parcelada'), ('RECEITA AVULSA', 'Despesa Avulsa')], default='', max_length=1000),
        ),
    ]
