# Generated by Django 4.2 on 2023-04-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_remove_registro_financeiro_origem_despesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_financeiro',
            name='origem_debito',
            field=models.CharField(choices=[('CARTAO ITAU MASTER CARD PLATINUM', 'Cartão Itaú Master Platinum'), ('CARTAO ITAU VISA PLATINUM', 'Cartão Itaú Visa Platinum'), ('CARTAO ITAU PAO DE ACUCAR VISA PLATINUM', 'Cartão Itaú Pão de Açucar Visa Platinum'), ('CARTAO ITAU XP VISA_INFINITIVE', 'Cartão Itaú XP Visa Infinitive'), ('CARTAO MERCADO PAGO VISA', 'Cartão Mercado Pago'), ('CONTA CORRENTE ITAU AG8584CC285855', 'Conta Corrente Itaú AG8584 CC285855')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registro_financeiro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
