# Generated by Django 4.2 on 2023-04-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_alter_registro_financeiro_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_financeiro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='registro_financeiro',
            name='origem_credito',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='registro_financeiro',
            name='tipo_categoria',
            field=models.CharField(choices=[('DESPESA FIXA', 'Despesa Fixa'), ('RECEITA PARCELADA', 'Despesa Parcelada'), ('RECEITA AVULSA', 'Despesa Avulsa'), ('RECEITA FIXA', 'Receita Fixa'), ('RECEITA PARCELADA', 'Receita Parcelada'), ('RECEITA AVULSA', 'Receita Avulsa')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registro_financeiro',
            name='competencia',
            field=models.CharField(choices=[('JANEIRO/2023', 'Janeiro/2023'), ('FEVEREIRO/2023', 'Fevereiro/2023'), ('MARCO/2023', 'Março/2023'), ('ABRIL/2023', 'Abril/2023'), ('MAIO/2023', 'Maio/2023'), ('JUNHO/2023', 'Junho/2023'), ('JULHO/2023', 'Julho/2023'), ('AGOSTO/2023', 'Agosto/2023'), ('SETEMBRO/2023', 'Setembro/2023'), ('OUTUBRO/2023', 'Outubro/2023'), ('NOVEMBRO/2023', 'Novembro/2023'), ('DEZEMBRO/2023', 'Dezembro/2023')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registro_financeiro',
            name='vencimento',
            field=models.CharField(choices=[('JANEIRO/2023', 'Janeiro/2023'), ('FEVEREIRO/2023', 'Fevereiro/2023'), ('MARCO/2023', 'Março/2023'), ('ABRIL/2023', 'Abril/2023'), ('MAIO/2023', 'Maio/2023'), ('JUNHO/2023', 'Junho/2023'), ('JULHO/2023', 'Julho/2023'), ('AGOSTO/2023', 'Agosto/2023'), ('SETEMBRO/2023', 'Setembro/2023'), ('OUTUBRO/2023', 'Outubro/2023'), ('NOVEMBRO/2023', 'Novembro/2023'), ('DEZEMBRO/2023', 'Dezembro/2023')], default='', max_length=1000),
        ),
    ]
