# Generated by Django 4.2 on 2023-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_remove_registro_financeiro_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_financeiro',
            name='origem_credito',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
