# Generated by Django 4.2 on 2023-04-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_alter_registro_financeiro_origem_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_financeiro',
            name='origem_credito',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
